(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(git--timer-sec 1.0)
 '(git-state-modeline-decoration (quote git-state-decoration-colored-letter))
 '(git-working-dir-change-behaviour (quote git-refresh-all-saved))
 '(send-mail-function (quote sendmail-send-it))
 '(vc-follow-symlinks t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(erb-comment-delim-face ((t (:background "brightblack" :foreground "red" :weight thin))))
 '(erb-comment-face ((t (:background "brightblack" :foreground "red" :weight thin))))
 '(erb-delim-face ((t (:background "brightblack" :foreground "blue" :weigth thin))))
 '(erb-exec-delim-face ((t (:background "brightblack" :foreground "red" :weight thin))))
 '(erb-exec-face ((t (:background "brightblack" :foreground "white" :weight thin))))
 '(erb-out-delim-face ((t (:background "brightblack") :foreground "red" :weight thin)))
 '(erb-out-face ((t (:background "brightblack" :foreground "white" :weight thin))))
 '(flymake-errline ((t (:background "red"))))
 '(font-lock-builtin-face ((t (:foreground "#CACACA"))))
 '(font-lock-comment-face ((t (:foreground "#5F5A60"))))
 '(font-lock-constant-face ((t (:foreground "#CF6A4C"))))
 '(font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
 '(font-lock-function-name-face ((t (:foreground "#9B703F"))))
 '(font-lock-keyword-face ((t (:foreground "#CDA869"))))
 '(font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
 '(font-lock-reference-face ((t (:foreground "SlateBlue"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "red"))))
 '(font-lock-string-face ((t (:foreground "#8F9D6A"))))
 '(font-lock-type-face ((t (:foreground "#9B703F"))))
 '(font-lock-variable-name-face ((t (:foreground "#7587A6"))))
 '(font-lock-warning-face ((t (:background "#EE799F" :foreground "red"))))
 '(highlight ((t (:background "#333333"))))
 '(highline-face ((t (:background "SeaGreen"))))
 '(hl-line ((t (:background "#212121"))))
 '(ido-first-match ((t (:foreground "#8F9D6A"))))
 '(ido-only-match ((t (:foreground "#8F9D6A"))))
 '(ido-subdir ((t (:foreground "#CF6A4C"))))
 '(left-margin ((t (nil))))
 '(linum ((t (:background "#141314" :foreground "#2D2B2E"))))
 '(minibuffer-prompt ((t (:foreground "#5F5A60"))))
 '(mode-line ((t (:background "grey10" :foreground "grey40" :height 0.8))))
 '(mode-line-inactive ((t (:background "grey75" :foreground "#111111" :box (:line-width -1 :color "grey20") :height 0.8))))
 '(mumamo-background-chunk-submode ((t (:background "#222222"))))
 '(quote (ruby-string-delimiter-face ((t (:foreground "#5A6340")))))
 '(region ((t (:background "#373446"))))
 '(ruby-heredoc-delimiter-face ((t (:foreground "#9B859D"))))
 '(ruby-op-face ((t (:foreground "#CDA869"))))
 '(ruby-regexp-delimiter-face ((t (:foreground "orange"))))
 '(sh-quoted-exec ((t (:foreground "brightmagenta"))))
 '(text-cursor ((t (:background "yellow" :foreground "black"))))
 '(toolbar ((t (nil))))
 '(underline ((nil (:underline nil))))
 '(yas/field-highlight-face ((t (:background "#27292A"))))
 '(zmacs-region ((t (:background "snow" :foreground "blue")))))
