(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(fill-column 72)
 '(font-lock-mode-maximum-decoration t)
 '(gist-authenticate-function (quote gist-basic-authentication) t)
 '(gist-view-gist t t)
 '(github-user "jpablobr" t)
 '(global-font-lock-mode t nil (font-lock))
 '(indent-tabs-mode nil)
 '(scroll-preserve-screen-position t)
 '(user-details (quote "Jose Pablo Barrantes R. http://jpablobr.com"))
 '(user-full-name (quote "Jose Pablo Barrantes R."))
 '(user-login-name "jpablobr" t)
 '(user-mail-address (quote "xjpablobrx@gmail.com"))
 '(vc-follow-symlinks t)
 '(w3m-arrived-file "~/Dropbox/private-dotfiles/w3m/.arrived")
 '(w3m-bookmark-file "~/Dropbox/private-dotfiles/w3m/bookmark.html" t)
 '(w3m-default-save-directory "~/Dropbox/private-dotfiles/w3m")
 '(w3m-form-textarea-directory "~/Dropbox/private-dotfiles/w3m/.textarea")
 '(w3m-profile-directory "~/Dropbox/private-dotfiles/w3m")
 '(w3m-session-file "~/Dropbox/private-dotfiles/w3m/.sessions"))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :family "apple-inconsolata"))))
 '(autoface-default ((t (:inherit default :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :family "apple-inconsolata"))))
 '(diff-added ((((background dark)) (:foreground "#FFFF9B9BFFFF")) (t (:foreground "DarkGreen"))))
 '(diff-changed ((((background dark)) (:foreground "Yellow")) (t (:foreground "MediumBlue"))))
 '(diff-context ((((background dark)) (:foreground "White")) (t (:foreground "Black"))))
 '(diff-file-header ((((background dark)) (:foreground "Cyan" :background "Black")) (t (:foreground "Red" :background "White"))))
 '(diff-function ((t (:foreground "#00bbdd"))))
 '(diff-header ((((background dark)) (:foreground "Cyan")) (t (:foreground "Red"))))
 '(diff-hunk-header ((((background dark)) (:foreground "Black" :background "#05057F7F8D8D")) (t (:foreground "White" :background "Salmon"))))
 '(diff-index ((((background dark)) (:foreground "Magenta")) (t (:foreground "Green"))))
 '(diff-nonexistent ((((background dark)) (:foreground "#FFFFFFFF7474")) (t (:foreground "DarkBlue"))))
 '(diff-refine-change ((((class color) (min-colors 88) (background dark)) (:background "#182042"))))
 '(diff-removed ((((background dark)) (:foreground "#7474FFFF7474")) (t (:foreground "DarkMagenta"))))
 '(lazy-highlight ((((class color) (min-colors 88) (background dark)) (:foreground "green" :underline t))))
 '(mumamo-background-chunk-major ((((class color) (min-colors 88) (background dark)) nil)))
 '(mumamo-background-chunk-submode ((((class color) (min-colors 88) (background dark)) nil)))
 '(mumamo-background-chunk-submode1 ((((class color) (min-colors 88) (background dark)) nil)))
 '(mumamo-background-chunk-submode2 ((((class color) (min-colors 88) (background dark)) nil)))
 '(mumamo-background-chunk-submode3 ((((class color) (min-colors 88) (background dark)) nil)))
 '(mumamo-background-chunk-submode4 ((((class color) (min-colors 88) (background dark)) nil)))
 '(query-replace ((t (:background "green" :foreground "white"))))
 '(test-failure ((t (:background "black" :foreground "ff3333" :weight bold :height 140 :family "arial"))) t)
 '(test-heading1 ((t (:background "#000000" :foreground "#9999ff" :weight bold :height 140 :family "arial"))) t)
 '(test-heading2 ((t (:background "#000000" :foreground "#9999ff" :weight bold :height 140 :family "arial"))) t)
 '(test-success ((t (:foreground "#33ff33" :weight bold :height 140 :family "arial"))) t)
 '(whitespace-line ((t (:background "purple" :foreground "green")))))
