(setq ruby-dir (concat vendor-dir "/ruby"))
(add-to-list 'load-path ruby-dir)
(load-file (concat jpablobr-lib "/jp-lib-ruby.el"))
(load-file (concat ruby-dir "/ruby-comint.el/ruby-comint.el"))
;; (load-file (concat ruby-dir "/ruby-electric.el"))

(require 'align)
(require 'inf-ruby)
(require 'jp-lib-ruby)
(require 'ruby-comint)
;; (require 'ruby-electric)
(require 'ruby-style)
(require 'flymake-ruby)
(require 'ruby-hacks)

(autoload 'ruby-mode "ruby-mode" "Major mode for ruby files" t)
(autoload 'toggle "toggle" nil t)

;; We never want to edit Rubinius bytecode
(add-to-list 'completion-ignored-extensions ".rbc")
(add-to-list 'interpreter-mode-alist '("ruby" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rake$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.gemspec$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.ru$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.Rakefile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\Gemfile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.Capfile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.Vagrantfile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.builder$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rb$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rhtml$" . rhtml-mode))
(add-to-list 'auto-mode-alist '("\\.html.erb$" . rhtml-mode))
(add-to-list 'auto-mode-alist '("\\.erb$" . rhtml-mode))
(add-to-list 'auto-mode-alist '("\\.sake\\'" . ruby-mode))

;; work around possible elpa bug
(ignore-errors (require 'ruby-compilation))
(setq ruby-use-encoding-map nil)

(add-hook 'ruby-mode-hook
          '(lambda ()
             (set (make-local-variable 'tab-width) 2)
             (highlight-parentheses-mode t)
             (highlight-symbol-mode t)
             (flymake-ruby-load)
             ;; (r-ruby-complexity)
             ;; (ruby-electric-mode t)
             (modify-syntax-entry ?! "w" (syntax-table))
             (modify-syntax-entry ?: "w" (syntax-table))
             (modify-syntax-entry ?_ "w" (syntax-table))
             (local-set-key (kbd "C-.") 'complete-tag)
             (inf-ruby-keys)
             (local-set-key [return] 'ruby-reindent-then-newline-and-indent)
             (define-key ruby-mode-map (kbd "RET") 'reindent-then-newline-and-indent)
             (local-set-key (kbd "<return>") 'newline-and-indent)))

(add-hook 'inf-ruby-mode-hook 'ansi-color-for-comint-mode-on)
(setq rdebug-short-key-mode t)

(provide 'jp-ruby)