(setq theaming-dir (concat vendor-dir "/theaming"))
;; (add-to-list 'load-path theaming-dir)
;; (require 'color-theme)

;; (add-to-list 'load-path (concat theaming-dir "/solarized"))
;; (require 'color-theme-solarized)
;; (color-theme-solarized-dark)

;; (load-file (concat theaming-dir "/color-theme-zenburn.el"))
;; (color-theme-zenburn)

(custom-set-faces
 '(hl-line ((t (:background "#4f4f4f"))))
 '(isearch ((((class color) (min-colors 8)) (:background "green" :foreground "black"))))
 '(erb-delim-face ((t (:background "black" :foreground "blue" :weigth thin))))
 '(erb-exec-face ((t (:background "black" :foreground "white" :weight thin))))
 '(erb-exec-delim-face ((t (:background "black" :foreground "red" :weight thin))))
 '(erb-out-face ((t (:background "black" :foreground "white" :weight thin ))))
 '(erb-out-delim-face ((t (:background "black") :foreground "red" :weight thin)))
 '(erb-comment-face ((t (:background "black" :foreground "red" :weight thin))))
 '(erb-comment-delim-face ((t (:background "black" :foreground "red" :weight thin)))))

;; '(region ((t (:foreground nil :background "#333333")))))
;;  '(mode-line ((t (:foreground "#222222" :background "#94bff3"))))
;;  '(font-lock-comment-face ((t (:foreground "#7f9f7f"))))
;;  '(font-lock-builtin-face ((t (:foreground "#8cd0d3"))))
;;  '(font-lock-comment-face ((t (:foreground "#7f9f7f"))))
;;  '(font-lock-comment-delimiter-face ((t (:foreground "#7f9f7f"))))
;;  '(font-lock-constant-face ((t (:foreground "#bfebbf"))))
;;  '(font-lock-doc-face ((t (:foreground "#8fb28f"))))
;;  '(font-lock-doc-string-face ((t (:foreground "#94bff3"))))
;;  '(font-lock-function-name-face ((t (:foreground "#8cd0d3"))))
;;  '(font-lock-keyword-face ((t (:foreground "#f0dfaf" :weight bold))))
;;  '(font-lock-negation-char-face ((t (:foreground "#dcdccc"))))
;;  '(font-lock-preprocessor-face ((t (:foreground "#8cd0d3"))))
;;  '(font-lock-string-face ((t (:foreground "#cc9393"))))
;;  '(font-lock-type-face ((t (:foreground "#8cd0d3"))))
;;  '(font-lock-variable-name-face ((t (:foreground  "#dfaf8f"))))
;; '(default ((t (:slant normal :weight normal :height 100 :width normal :family "Monospace"))))
;; '(test-failure ((t (:background "#3f3f3f" :foreground "#8c5353" :weight bold :height 140 :family "arial"))) t)
;; '(test-heading1 ((t (:background "#3f3f3f" :foreground "#9999ff" :weight bold :height 140 :family "arial"))) t)
;; '(test-heading2 ((t (:background "#3f3f3f" :foreground "#9999ff" :weight bold :height 140 :family "arial"))) t)
;; '(test-success ((t (:background "#3f3f3f" :foreground "#5f7f5f" :weight bold :height 140 :family "arial"))) t))

(provide 'jp-theme)